stages:
  # - test
  - build
  - deploy
  - migrate
  

include:
  - local: 'apps/api/.gitlab-ci.yml'

variables:
  REGISTRY: registry.booulder.xyz
  IMAGE: $REGISTRY/$CI_PROJECT_PATH
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_TLS_CERTDIR: ""

# typecheck:
#   stage: test
#   image: oven/bun:latest
#   allow_failure: true
#   script:
#     - bun install
#     - bun run build
#     - bun run typecheck

# test:
#   stage: test
#   image: oven/bun:latest
#   script:
#     - bun install
#     - bun run test
  # artifacts:
  #   when: always
    # paths:
    #   - bun.xml
    # reports:
    #   junit: bun.xml

